version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis